[package]
name = "graph-owl-server"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
graph-owl-api.workspace = true
graph-owl-connectors.workspace = true
graph-owl-ui.workspace = true
graph-owl-authz.workspace = true
jsonwebtoken = "9"
graph-owl-core.workspace = true
graph-owl-storage.workspace = true
graph-owl-storage-postgres.workspace = true
graph-owl-engine-postgres.workspace = true
chrono.workspace = true
axum.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true

[dev-dependencies]
jsonwebtoken = "9"
sqlx.workspace = true
tower.workspace = true
testcontainers-modules.workspace = true

[lints]
workspace = true
