/** Every user-visible literal lives here, not inline in JSX — enforced by
 *  `eslint-rules/no-raw-jsx-text.mjs` (ported from `ui/`, Epic 39 Slice E
 *  decision 7: "No user-visible literal in a component," so i18n never
 *  needs a retrofit). */
export const strings = {
  brand: "GRAPHOWL",
  searchPlaceholder: "Search or ask GraphOWL…",
  searchShortcut: "⌘K",
  themeDay: "DAY",
  themeNight: "NIGHT",
  inboxTitle: "Waiting on you",
  inboxSubtitle: "agents queue here; nothing applies itself",
  inboxFooter:
    "Automatic agents never reach this list — they only read. Anything that would change the graph lands here first.",
  inboxEmpty: "Nothing waiting on you right now.",
  approve: "Approve",
  reject: "Reject",
  close: "Close",
  collapseNav: "COLLAPSE",
  workspaceHeading: "WORKSPACE · ISOLATED GRAPH + PACKS",
  workspaceFooter: "Switching changes the graph, the installed packs and the audit trail. Nothing is shared between workspaces.",
  workspaceSingleNote: "Multi-workspace isolation is not yet available — every session uses this one workspace.",
  searchIcon: "⌕",
  inboxIcon: "⚑",
  closeIcon: "×",
  inboxReasonPlaceholder: "Why? (required)",
  inboxReasonConfirm: "Confirm reject",
  inboxReasonCancel: "Cancel",
  inboxActionFailed: "That didn't go through — try again.",
  searchNoResults: "No matches.",
  searchFailed: "Search failed to load.",
  searchAsset: "ASSET",
  searchGlossaryTerm: "GLOSSARY TERM",
  searchBusinessMetric: "BUSINESS METRIC",
  overviewTitle: "Knowledge graph overview",
  overviewLoading: "Loading…",
  overviewError: "Could not load the overview — try again.",
  overviewAssetsTotal: "ASSETS",
  overviewDocumentation: "DOCUMENTED",
  overviewGraphFlakes: "GRAPH FACTS",
  overviewGraphNodes: "GRAPH NODES",
  overviewGraphEdges: "GRAPH EDGES",
  overviewGraphHealth: "GRAPH HEALTH",
  overviewCoverage: "Coverage",
  overviewGovernance: "Governance",
  overviewRecentActivity: "RECENT ACTIVITY",
  overviewNoActivity: "Nothing changed recently.",

  // ---- Explore (Plan 122a A3) ----
  exploreNoSeed: "Search or open an entity to explore its neighbourhood.",
  exploreLoading: "Loading the neighbourhood…",
  exploreError: "Could not load this neighbourhood — try again.",
  exploreFullscreenEnter: "Full screen",
  exploreFullscreenExit: "Exit full screen",
  exploreClose: "✕",
  exploreKind: "Kind",
  exploreKindHidden: "hidden by authorization",
  exploreId: "Id",
  exploreFqn: "Fully qualified name",
  exploreOpenEntity: "Open entity",
  explorePinToInvestigation: "Pin to investigation",
  explorePinned: "Pinned.",
  explorePinFailed: "Could not pin this — try again.",
  exploreEdgeAsserted: "ASSERTED",
  exploreEdgeDerived: "INFERRED",
  exploreTracePath: "Trace path to seed",
  exploreTruncated: "This picture is incomplete — some neighbours were cut off.",
  exploreRelationshipFilter: "Relationship",
  exploreClearFilter: "Clear filters",
  exploreTitle: "Explore",
  exploreBreadcrumbSeparator: "/",

  // ---- Entity (Plan 122a A3) ----
  entityNoId: "Search or open an entity to inspect it.",
  entityLoading: "Loading…",
  entityError: "Could not load this entity — try again.",
  entityOpenInExplorer: "Open in Explorer",
  entityPinToInvestigation: "Pin to investigation",
  entityFacts: "FACTS",
  entityFactsEmpty: "No outgoing relationships recorded for this entity.",
  entityFactAsserted: "asserted",
  entityFactDerived: "derived",
  entityContradictionTitle: "CONTRADICTION",
  entityContradictionDivider: "≠",
  entityContradictionHint: "Neither is hidden until you decide.",
  entityConfirm: "Confirm — these disagree",
  entityDismiss: "Dismiss — not a conflict",
  entityDismissTitle: "Dismiss this pair?",
  entityDismissBody: "It will not be flagged again. Both memories stay exactly as they are.",
  entityDismissCancel: "Cancel",
  entityContradictionConfirmed: "Recorded — the pair stays flagged, because agreeing it exists is not settling it.",
  entityContradictionDismissed: "Dismissed.",
  entityContradictionActionFailed: "That verdict could not be recorded — try again.",
  entityContradictionSideMissing: "not shown here — may be below this view's confidence floor",
  entityHistory: "HISTORY",
  entityHistoryEmpty: "No prior versions.",
  entityImpact: "IMPACT IF CHANGED",
  entityImpactEmpty: "Nothing else in the graph points to this entity yet.",

  // ---- TRACE group — Lineage, Paths, History, Evidence (Plan 122a A4) ----
  relatedTitle: "RELATED",
  traceRelatedExplore: "Explore",
  traceRelatedEntity: "Entity",
  traceRelatedContradictions: "Contradictions",
  traceNoSeed: "Search or open an entity to trace it.",
  traceLoading: "Loading…",
  traceError: "Could not load this — try again.",

  lineageTitle: "Lineage & impact",
  lineageDescription: "Where a fact came from, and what breaks if it changes.",
  lineageKpiFocus: "FOCUS",
  lineageKpiUpstream: "UPSTREAM",
  lineageKpiDownstream: "DOWNSTREAM",
  lineageKpiTruncated: "COMPLETE PICTURE",
  lineageTruncatedYes: "no — some edges cut off",
  lineageTruncatedNo: "yes",
  lineageColRelationship: "RELATIONSHIP",
  lineageColFrom: "FROM",
  lineageColTo: "TO",
  lineageColSource: "SOURCE",
  lineageColWhen: "WHEN",
  lineageEmpty: "No lineage edges recorded for this entity.",
  lineageChainArrow: "→",
  lineageChainSeparator: "·",
  lineageChainNodes: "nodes",
  lineageNoteTitle: "WHAT THIS SHOWS",
  lineageNoteBody: "Every asserted lineage edge within two hops of this entity, upstream and downstream. Nothing here is inferred — each edge was declared by a person, a connector, or an OpenLineage run event.",

  pathsTitle: "Path finder",
  pathsDescription: "How are these two things connected?",
  pathsKpiFrom: "FROM",
  pathsKpiTo: "TO",
  pathsKpiFound: "PATHS FOUND",
  pathsKpiTruncated: "COMPLETE PICTURE",
  pathsColPath: "PATH",
  pathsColRoute: "ROUTE",
  pathsColHops: "HOPS",
  pathsEmpty: "No path found between these two entities within the search bound.",
  pathsNoteTitle: "READ EVERY PATH, NOT JUST THE FIRST",
  pathsNoteBody: "A weak or roundabout connection is still shown, ranked by hop count — you decide whether it counts as a real connection.",
  pathsMissingEnds: "Provide both a from and a to entity to search.",
  pathsFromLabel: "From",
  pathsToLabel: "To",
  pathsSearch: "Find paths",

  historyTitle: "History & diff",
  historyDescription: "What the graph believed then, and what changed since.",
  historyKpiEntity: "ENTITY",
  historyKpiVersions: "VERSIONS",
  historyKpiLatest: "LATEST",
  historyKpiUpdatedBy: "LAST CHANGED BY",
  historyColVersion: "VERSION",
  historyColChange: "CHANGE",
  historyColWho: "WHO",
  historyColWhen: "WHEN",
  historyNoSummary: "no summary recorded",
  historyEmpty: "No prior versions recorded for this entity.",
  historyNoteTitle: "TIME IS GLOBAL",
  historyNoteBody: "Every version this entity has ever had, oldest first. Time-travel elsewhere in the console (Explore, Entity) reads against the same version history.",

  evidenceTitle: "Evidence",
  evidenceDescription: "Every governance finding, and the facts it rests on.",
  evidenceKpiFindings: "FINDINGS",
  evidenceKpiEntries: "EVIDENCE ENTRIES",
  evidenceKpiPending: "PENDING REVIEW",
  evidenceKpiPacks: "PACKS INVOLVED",
  evidenceColFact: "FACT",
  evidenceColSource: "PACK",
  evidenceColField: "FIELD",
  evidenceColStatus: "STATUS",
  evidenceEmpty: "No findings recorded yet.",
  evidenceNoteTitle: "WHERE THIS COMES FROM",
  evidenceNoteBody: "Every governance finding carries the facts that produced it — a rule concluded something, and this is what it looked at to conclude it.",

  // ---- GOVERN group — Validation, Resolution, Drift, Governance (Plan 122a A5) ----
  governLoading: "Loading…",
  governError: "Could not load this — try again.",
  governInspect: "Inspect",
  governClose: "Close",
  governCancel: "Cancel",
  governBothArrow: "↔",
  governSelectedSuffix: "selected",
  governRulesSuffix: "rules",
  governNoRoles: "no roles",

  validationTitle: "Validation",
  validationDescription: "SHACL shapes, checked on every write. Nothing here is rejected — reported.",
  validationKpiViolations: "VIOLATIONS",
  validationKpiWarnings: "WARNINGS",
  validationKpiAffected: "AFFECTED",
  validationKpiWaived: "WAIVED",
  validationColShape: "SHAPE",
  validationColFocusNode: "FOCUS NODE",
  validationColConstraint: "CONSTRAINT",
  validationColSeverity: "SEVERITY",
  validationColStatus: "STATUS",
  validationEmpty: "No violations recorded.",
  validationStatusWaived: "waived",
  validationStatusAssigned: "assigned",
  validationStatusOpen: "open",
  validationWaiveTitle: "Waive this finding",
  validationWaiveReason: "Reason (required)",
  validationWaiveExpiry: "Expires",
  validationWaiveSubmit: "Waive",
  validationRevokeWaiver: "Revoke waiver",
  validationAssignTitle: "Assign this finding",
  validationAssigneePlaceholder: "user id",
  validationAssignSubmit: "Assign",
  validationUnassign: "Unassign",

  resolutionTitle: "Entity resolution",
  resolutionDescription: "Candidate matches from blocking and similarity scoring. Humans confirm.",
  resolutionKpiPending: "IN QUEUE",
  resolutionKpiConfirmed: "CONFIRMED",
  resolutionKpiRejected: "REJECTED",
  resolutionKpiSelected: "SELECTED",
  resolutionColTarget: "TARGET",
  resolutionColCandidate: "CANDIDATE",
  resolutionColScore: "SCORE",
  resolutionColEvidence: "EVIDENCE",
  resolutionEmpty: "Nothing pending review.",
  resolutionConfirm: "Confirm match",
  resolutionReject: "Reject match",
  resolutionRejectReason: "Reason (required)",
  resolutionBulkConfirm: "Confirm selected",
  resolutionBulkReject: "Reject selected",
  resolutionBulkPreviewTitle: "This will affect exactly these entries",
  resolutionBulkConfirmGo: "Confirm all",
  resolutionBulkRejectGo: "Reject all",

  driftTitle: "Drift",
  driftDescription: "The source changed shape or behaviour. Decide before it propagates. Drift is not an error.",
  driftKpiPending: "OPEN",
  driftKpiApplied: "APPLIED",
  driftKpiIgnored: "IGNORED",
  driftKpiAssets: "ASSETS AFFECTED",
  driftColField: "FIELD",
  driftColLive: "LIVE",
  driftColDeclared: "DECLARED",
  driftColKind: "KIND",
  driftEmpty: "No drift reported.",
  driftApply: "Apply",
  driftIgnore: "Ignore",
  driftIgnoreReason: "Reason (required)",
  driftApplyUnavailable: "Only the description field can be applied automatically here.",

  governanceTitle: "Governance",
  governanceDescription: "Policies compiled to access decisions. Compose, dry-run, then save.",
  governanceKpiCertified: "CERTIFIED, EXPIRING ≤ 90D",
  governanceKpiUnowned: "UNOWNED ASSETS",
  governanceKpiDeprecated: "DEPRECATED",
  governanceKpiRetired: "RETIRED",
  governanceNewPolicy: "New policy",
  governancePolicyName: "Policy name",
  governanceRoles: "Roles (comma-separated)",
  governanceAddRule: "Add rule",
  governanceRuleName: "Rule name",
  governanceEffect: "Effect",
  governanceOperations: "Operations",
  governanceResourceType: "Resource",
  governanceResourceValue: "Value",
  governanceDryRun: "Dry run",
  governanceSave: "Save policy",
  governanceDelete: "Delete",
  governanceDryRunAdmitted: "ADMITTED",
  governanceDryRunDenied: "DENIED",
  governanceDryRunTotal: "TOTAL",
  governanceAdmitsEverything: "This policy admits everything in the estate — every rule is effectively a no-op.",
  governanceDeniesEverything: "This policy denies everything in the estate — nobody would see anything under it.",
  governanceEmpty: "No policies saved yet.",

  contradictionsTitle: "Contradictions",
  contradictionsDescription: "Two sources assert incompatible facts about the same entity. Nothing is auto-hidden.",
  contradictionsScopeNote: "GraphOWL reviews contradictions per entity, not as a single catalog-wide queue — there is no aggregate list yet. Open an entity's Contradictions to review what it disagrees with itself about.",
  contradictionsSearchPlaceholder: "Entity id",
  contradictionsSearchSubmit: "Open entity",

  // ---- INGEST group — Sources, Connectors (Plan 122a A6) ----
  sourcesTitle: "Sources",
  sourcesDescription: "Every fact in the graph traces back to one of these — rolled up from connector run history.",
  sourcesKpiCount: "SOURCES",
  sourcesKpiObjects: "OBJECTS",
  sourcesKpiStale: "STALE",
  sourcesKpiRuns: "RUNS RECORDED",
  sourcesColSource: "SOURCE",
  sourcesColConnector: "CONNECTOR",
  sourcesColObjects: "OBJECTS",
  sourcesColLastSync: "LAST SYNC",
  sourcesColHealth: "HEALTH",
  sourcesEmpty: "No connector runs recorded yet.",
  sourcesHealthHealthy: "healthy",
  sourcesHealthStale: "stale",
  sourcesHealthDegraded: "degraded",
  sourcesNoteTitle: "WHAT THIS SHOWS",
  sourcesNoteBody: "Objects created minus deleted, summed across every recorded run for this service. A source is stale after 7 days with no sync, and degraded when its most recent run reported a failure.",
  sourcesRunHistory: "RUN HISTORY",
  sourcesColStarted: "STARTED",
  sourcesColCreated: "CREATED",
  sourcesColSkipped: "SKIPPED",
  sourcesColFailed: "FAILED",
  sourcesColDeleted: "DELETED",
  sourcesColTriggeredBy: "TRIGGERED BY",
  runPrefixCreated: "+",
  runPrefixSkipped: "~",
  runPrefixFailed: "!",
  runPrefixDeleted: "-",

  connectorsTitle: "Connectors",
  connectorsDescription: "Connector types this catalog can pull from.",
  connectorsPostgresName: "Postgres",
  connectorsPostgresDescription: "Introspects a Postgres database's schemas, tables and columns as assets.",
  connectorsTestTitle: "Test connection",
  connectorsTestSubmit: "Test connection",
  connectorsTestOk: "Connection succeeded.",
  connectorsRunTitle: "Run sync",
  connectorsServiceName: "Service name",
  connectorsRunSubmit: "Run sync",
  connectorsRunResult: "RUN RESULT",

  // ---- Vocabulary Studio (Plan 122a A7) ----
  studioTitle: "Vocabulary Studio",
  studioDescription: "Glossary terms, semantic relations, and how they're used across the catalog.",
  studioTabBuild: "Build",
  studioTabGlossary: "Glossary",
  studioTabBusiness: "Business view",
  studioTabProposals: "Proposals",
  studioTabGraph: "Graph",
  studioTabValidate: "Validate",
  studioTabSparql: "SPARQL",
  studioTabExport: "Export",
  studioGlossaryPicker: "Glossary",
  studioNewGlossary: "New glossary",
  studioGlossaryNamePlaceholder: "Glossary name",
  studioNoGlossaries: "No glossaries yet — create one to get started.",
  studioLoading: "Loading…",
  studioError: "Could not load this — try again.",

  buildTreeEmpty: "This glossary has no terms yet.",
  buildDetailPlaceholder: "Select a term to see its detail, relations, and where it's used.",
  buildCyclicSuffix: " (cycle)",
  buildCyclicNotice: "This term and one of its ancestors declare each other as broader — shown once, here, to break the loop rather than repeat forever.",
  buildNewTerm: "New term",
  buildTermNamePlaceholder: "Term name",
  buildDefinition: "DEFINITION",
  buildStatus: "STATUS",
  buildSynonyms: "SYNONYMS",
  buildAbbreviations: "ABBREVIATIONS",
  buildRelations: "RELATIONS",
  buildNoRelations: "No relations recorded.",
  buildAddRelation: "Add relation",
  buildRemoveRelation: "×",
  buildRelationTarget: "Target term id",
  buildRelationKind: "Relation kind",
  buildUsage: "USED BY",
  buildNoUsage: "Not attached to anything yet.",
  buildDeleteTerm: "Delete term",

  glossaryStatusDraft: "draft",
  glossaryStatusInReview: "in review",
  glossaryStatusApproved: "approved",
  glossaryStatusDeprecated: "deprecated",
  glossaryCandidatesTitle: "CANDIDATES — DRAFT & IN REVIEW",
  glossaryApprovedTitle: "APPROVED",
  glossaryPromote: "Promote to approved",
  glossarySubmitForReview: "Submit for review",
  glossaryEmpty: "No terms in this glossary yet.",
  glossaryPromoteError: "Could not promote — approval needs at least one assigned reviewer first.",
  glossaryReviewerError: "Could not assign that reviewer — is it a known user id?",
  glossaryReviewerPlaceholder: "reviewer user id",
  glossaryAssignReviewer: "Assign reviewer",

  businessDescription: "Plain-language definitions only — no relations, no technical fields.",
  businessEmpty: "Nothing to show yet.",

  graphConnectTitle: "Connect two concepts",
  graphConnectFrom: "From",
  graphConnectTo: "To",
  graphConnectKind: "Relation",
  graphConnectSubmit: "Connect",
  graphEmpty: "This glossary has no terms to graph yet.",

  sparqlPlaceholder: "SELECT ?s ?p ?o WHERE { ?s ?p ?o } LIMIT 20",
  sparqlRun: "Run",
  sparqlRows: "ROWS",
  sparqlFactsScanned: "FACTS SCANNED",
  sparqlTruncated: "TRUNCATED",
  sparqlEmpty: "Run a query to see results.",
  sparqlNoRows: "Query returned no rows.",

  studioNotYetBuiltTitle: "Not yet built",
  studioNotYetBuiltProposals: "Candidate staging — a system-suggested altLabel or concept, with its source, count and match score — has no backend yet. See plans/122a-graphowl-app.md's A7.api for the gap.",
  studioNotYetBuiltValidate: "qSKOS checks have no backend yet — no check set is seeded, and no skos-shapes.ttl exists to run through /validation/shapes/seed. See plans/122a-graphowl-app.md's A7.api for the gap.",
  studioNotYetBuiltExport: "Vocabulary-scoped RDF export (Turtle / JSON-LD / RDF-XML / N-Triples) has no backend yet. See plans/122a-graphowl-app.md's A7.api for the gap.",

  // ---- Analytics (Plan 122a A9) ----
  analyticsTitle: "Analytics",
  analyticsDescription: "Graph health, inference yield, and model spend — what the engine is doing, not what you asked it.",
  analyticsShowFacts: "Show the facts",
  analyticsBuildReport: "Build report",
  analyticsGrowthTitle: "GRAPH GROWTH BY FACT STATE",
  analyticsGrowthNote: "Inferred facts are growing faster than asserted ones. That is the pack doing work, not more data arriving.",
  analyticsFunnelTitle: "FROM SOURCE ROW TO CERTIFIED FACT",
  analyticsFunnelNote: "Each step loses something — that is the point.",
  analyticsHeatmapTitle: "CONFIDENCE DECAY BY PREDICATE",
  analyticsHotspotsTitle: "MOST-TRAVERSED RELATIONSHIPS",
  analyticsNarrativeTitle: "READ OF THE PERIOD",
  analyticsNarrativeBody: "Inference yield rose to 1.54× after the GST pack added the filing-period rules, which is where most of the new facts came from — not new sources. Confidence on filingPeriod fell five months running because two sources now disagree about late filings; that decay is why cross-period cases exist downstream in Reco Now.",
  analyticsNarrativeCite: "31 facts cited · written from the graph, not from the dashboard",
  analyticsModelSpendTitle: "MODEL SPEND VS GRAPH WORK",
  analyticsModelSpendNote: "Retrieval and reasoning are graph work, not model work. The model is only paid for the sentence at the end.",

  // ---- Agents, MCP, Runs (Plan 122a A8 — real subset) ----
  agentsTitle: "Agents & model usage",
  agentsDescription: "Agents call GraphOWL capabilities through MCP. Every claim is grounded in a graph fact; every write is gated by a human.",
  agentsKpiGrants: "GRANTED",
  agentsKpiCapabilities: "CAPABILITIES IN USE",
  agentsKpiExpiring: "EXPIRING",
  agentsColAgent: "AGENT · PIPELINE STAGE",
  agentsColCapabilities: "CAPABILITIES",
  agentsColScope: "SCOPE",
  agentsColRateLimit: "RATE LIMIT",
  agentsColExpires: "EXPIRES",
  agentsColTrigger: "TRIGGER",
  agentsColRuns: "RUNS 24H",
  agentsColGrounding: "GROUNDING",
  agentsColControl: "CONTROL",
  agentsRateLimitSeparator: "/",
  agentsRateLimitSuffix: "s",
  agentsEmpty: "No agents granted yet.",
  agentsRevoke: "Revoke",
  agentsActivityTitle: "RECENT ACTIVITY",
  agentsActivityEmpty: "No activity recorded.",
  agentsScopeAll: "whole estate",
  agentsNoExpiry: "never",
  agentsNewGrant: "New agent",
  agentsPolicies: "Policies",
  agentsGrantAgentId: "Agent id",
  agentsGrantScope: "Scope FQN prefix (optional)",
  agentsGrantSubmit: "Grant",
  agentsPipelineTitle: "ONE PIPELINE, NOT FIVE SEPARATE BOTS",
  agentsPipelineSubtitle: "a finding enters left, leaves as an approved action",
  agentsPipelineNote: "Stages hand each other fact ids, not prose. If a stage cannot cite the graph the pipeline halts there and the case stays unexplained rather than guessed.",
  agentsRosterTitle: "AGENTS",
  agentsRosterSubtitle: "grounding = share of output backed by graph evidence",
  agentsTraceTitle: "RUN TRACE · GRAPH INVESTIGATOR",
  agentsTraceMeta: "run_8f21c · 4.2 s · 3,180 tok",
  agentsTraceQuestion: "Why is Supplier ABC linked to Company XYZ? — asked from Reco Now case INV-1025",
  agentsAnswerTitle: "ANSWER · 6 CITATIONS",
  agentsAnswerBody: "Supplier ABC and Company XYZ share a PAN and appear as the filing party on the same July GST return. Entity resolution links them at 0.94. The model wrote this sentence; every fact in it came from the graph.",
  agentsAnswerCite: "6 facts cited · written from the graph, not from the prompt",
  agentsModelTitle: "TOKENS BY MODEL · 30 DAYS",
  agentsSpendLabel: "Spend this month",
  agentsBudgetLabel: "Budget",
  agentsGuardrailsTitle: "GUARDRAILS",
  agentsMcpTitle: "MCP TOOLS EXPOSED",

  runsTitle: "Agent proposals",
  runsDescription: "What an agent suggested, and why — a proposal is the trace of one run's output.",
  runsKpiOpen: "OPEN",
  runsKpiAccepted: "ACCEPTED",
  runsKpiRejected: "REJECTED",
  runsColProposedBy: "PROPOSED BY",
  runsColTarget: "TARGET",
  runsColCapability: "CAPABILITY",
  runsColConfidence: "CONFIDENCE",
  runsColStatus: "STATUS",
  runsEmpty: "No proposals recorded.",
  runsRationale: "RATIONALE",
  runsChange: "PROPOSED CHANGE",
  runsAccept: "Accept",
  runsReject: "Reject",
  runsGapNote: "Tokens, latency, cited fact ids and per-model spend aren't tracked here — the proposal that resulted from a run is, which is what this queue shows. See plans/122a-graphowl-app.md's A8.api for the gap.",

  mcpTitle: "MCP",
  mcpDescription: "Tools exposed to agents over the MCP transport — one endpoint, thirteen tools.",
  mcpColName: "TOOL",
  mcpColDescription: "DESCRIPTION",
  mcpEmpty: "No tools reported.",

  // ---- PLATFORM — Workbench, Packs, Admin (Plan 122a A10) ----
  workbenchTitle: "Workbench",
  workbenchDescription: "Run a query directly against the graph.",
  workbenchTabSparql: "SPARQL",
  workbenchTabCypher: "Cypher",
  cypherPlaceholder: "MATCH (s)-[p]->(o) RETURN s, p, o LIMIT 20",

  packsTitle: "Packs",
  packsDescription: "Ontology packs available to install, and what's inside the ones you have.",
  packsEmpty: "No packs available to install — everything found is already installed.",
  packsInstall: "Install",
  packsInstalling: "Installing…",
  packsInstallResult: "INSTALL RESULT",
  packsTerms: "TERMS",
  packsOverrides: "OVERRIDES",
  packsOverridesEmpty: "No overrides.",
  packsAddOverride: "Add override",
  packsOverrideTermPath: "Term path",
  packsOverrideKind: "Kind",
  packsUpgrade: "UPGRADE",
  packsUpgradeVersion: "Target version",
  packsUpgradeManifest: "New pack.toml contents",
  packsDryRun: "Dry run",
  packsApply: "Apply upgrade",
  packsUpgradeApplied: "Applied.",
  packsUpgradePreview: "Preview only — nothing was written.",
  packsInspect: "Inspect",
  packsInstalledTitle: "INSTALLED",
  packsInstalledEmpty: "Nothing installed yet.",
  packsVersionPrefix: "v",
  packsTermsSuffix: "terms",

  adminTitle: "Administration",
  adminDescription: "Workspace, access and audit. No graph functionality lives here.",
  adminPrimaryAction: "Invite user",
  adminSecondaryAction: "Export audit",
  adminKpiUsers: "USERS",
  adminKpiApiKeys: "API KEYS",
  adminKpiSso: "SSO",
  adminKpiAuditEvents: "AUDIT EVENTS 24H",
  adminColActor: "ACTOR",
  adminColAction: "ACTION",
  adminColObject: "OBJECT",
  adminColTime: "TIME",
  adminColResult: "RESULT",
  adminChartTitle: "AUDIT EVENTS PER HOUR",
  adminChartSubtitle: "agent identities are audited exactly like people",
  adminCalloutTitle: "AGENT ACTIONS ARE AUDITED LIKE USERS",
  adminCalloutBody: "Every MCP call is attributed to an agent identity with the same audit trail a person gets, including denials.",

  // ---- PLATFORM — Tasks, Quality, Privacy, Security, API Keys ----
  tasksTitle: "Tasks",
  tasksDescription: "Open action items from contradictions, drift alerts, proposals, and agent grounding issues.",

  qualityTitle: "Quality",
  qualityDescription: "Graph health metrics — entity resolution precision, citation coverage, ontology completeness.",

  privacyTitle: "Privacy",
  privacyDescription: "PII tagging, masking policies, row-level security, and erasure request tracking.",

  securityTitle: "Security",
  securityDescription: "Auth events, access denials, token rotations, and policy changes.",

  apiKeysTitle: "API Keys",
  apiKeysDescription: "Manage API keys for external integrations, CI/CD pipelines, and service accounts.",
  apiKeysGenerate: "Generate key",
} as const;
