/** Every user-visible literal lives here, not inline in JSX — enforced by
 *  `eslint-rules/no-raw-jsx-text.mjs` (ported from `ui/`, Epic 39 Slice E
 *  decision 7: "No user-visible literal in a component," so i18n never
 *  needs a retrofit). */
export const strings = {
  brand: "GRAPHOWL",
  searchPlaceholder: "Search or ask GraphOWL…",
  searchShortcut: "⌘K",
  themeDay: "DAY",
  themeNight: "NIGHT",
  inboxTitle: "Waiting on you",
  inboxSubtitle: "agents queue here; nothing applies itself",
  inboxFooter:
    "Automatic agents never reach this list — they only read. Anything that would change the graph lands here first.",
  inboxEmpty: "Nothing waiting on you right now.",
  approve: "Approve",
  reject: "Reject",
  close: "Close",
  collapseNav: "COLLAPSE",
  workspaceHeading: "WORKSPACE · ISOLATED GRAPH + PACKS",
  workspaceFooter: "Switching changes the graph, the installed packs and the audit trail. Nothing is shared between workspaces.",
  workspaceSingleNote: "Multi-workspace isolation is not yet available — every session uses this one workspace.",
  searchIcon: "⌕",
  inboxIcon: "⚑",
  closeIcon: "×",
  inboxReasonPlaceholder: "Why? (required)",
  inboxReasonConfirm: "Confirm reject",
  inboxReasonCancel: "Cancel",
  inboxActionFailed: "That didn't go through — try again.",
  searchNoResults: "No matches.",
  searchAsset: "ASSET",
  searchGlossaryTerm: "GLOSSARY TERM",
  searchBusinessMetric: "BUSINESS METRIC",
  overviewTitle: "Knowledge graph overview",
  overviewLoading: "Loading…",
  overviewError: "Could not load the overview — try again.",
  overviewAssetsTotal: "ASSETS",
  overviewDocumentation: "DOCUMENTED",
  overviewGraphFlakes: "GRAPH FACTS",
  overviewGraphNodes: "GRAPH NODES",
  overviewGraphEdges: "GRAPH EDGES",
  overviewGraphHealth: "GRAPH HEALTH",
  overviewCoverage: "Coverage",
  overviewGovernance: "Governance",
  overviewRecentActivity: "RECENT ACTIVITY",
  overviewNoActivity: "Nothing changed recently.",

  // ---- Explore (Plan 122a A3) ----
  exploreNoSeed: "Search or open an entity to explore its neighbourhood.",
  exploreLoading: "Loading the neighbourhood…",
  exploreError: "Could not load this neighbourhood — try again.",
  exploreFullscreenEnter: "Full screen",
  exploreFullscreenExit: "Exit full screen",
  exploreClose: "✕",
  exploreKind: "Kind",
  exploreKindHidden: "hidden by authorization",
  exploreId: "Id",
  exploreFqn: "Fully qualified name",
  exploreOpenEntity: "Open entity",
  explorePinToInvestigation: "Pin to investigation",
  explorePinned: "Pinned.",
  explorePinFailed: "Could not pin this — try again.",
  exploreEdgeAsserted: "ASSERTED",
  exploreEdgeDerived: "INFERRED",
  exploreTracePath: "Trace path to seed",
  exploreTruncated: "This picture is incomplete — some neighbours were cut off.",
  exploreRelationshipFilter: "Relationship",
  exploreClearFilter: "Clear filters",
  exploreTitle: "Explore",
  exploreBreadcrumbSeparator: "/",

  // ---- Entity (Plan 122a A3) ----
  entityNoId: "Search or open an entity to inspect it.",
  entityLoading: "Loading…",
  entityError: "Could not load this entity — try again.",
  entityOpenInExplorer: "Open in Explorer",
  entityPinToInvestigation: "Pin to investigation",
  entityFacts: "FACTS",
  entityFactsEmpty: "No outgoing relationships recorded for this entity.",
  entityFactAsserted: "asserted",
  entityFactDerived: "derived",
  entityContradictionTitle: "CONTRADICTION",
  entityContradictionDivider: "≠",
  entityContradictionHint: "Neither is hidden until you decide.",
  entityConfirm: "Confirm — these disagree",
  entityDismiss: "Dismiss — not a conflict",
  entityDismissTitle: "Dismiss this pair?",
  entityDismissBody: "It will not be flagged again. Both memories stay exactly as they are.",
  entityDismissCancel: "Cancel",
  entityContradictionConfirmed: "Recorded — the pair stays flagged, because agreeing it exists is not settling it.",
  entityContradictionDismissed: "Dismissed.",
  entityContradictionActionFailed: "That verdict could not be recorded — try again.",
  entityContradictionSideMissing: "not shown here — may be below this view's confidence floor",
  entityHistory: "HISTORY",
  entityHistoryEmpty: "No prior versions.",
  entityImpact: "IMPACT IF CHANGED",
  entityImpactEmpty: "Nothing else in the graph points to this entity yet.",
} as const;
