/** Every user-visible literal lives here, not inline in JSX — enforced by
 *  `eslint-rules/no-raw-jsx-text.mjs` (ported from `ui/`, Epic 39 Slice E
 *  decision 7: "No user-visible literal in a component," so i18n never
 *  needs a retrofit). */
export const strings = {
  brand: "GRAPHOWL",
  searchPlaceholder: "Search or ask GraphOWL…",
  searchShortcut: "⌘K",
  themeDay: "DAY",
  themeNight: "NIGHT",
  inboxTitle: "Waiting on you",
  inboxSubtitle: "agents queue here; nothing applies itself",
  inboxFooter:
    "Automatic agents never reach this list — they only read. Anything that would change the graph lands here first.",
  inboxEmpty: "Nothing waiting on you right now.",
  approve: "Approve",
  reject: "Reject",
  close: "Close",
  collapseNav: "COLLAPSE",
  workspaceHeading: "WORKSPACE · ISOLATED GRAPH + PACKS",
  workspaceFooter: "Switching changes the graph, the installed packs and the audit trail. Nothing is shared between workspaces.",
  workspaceSingleNote: "Multi-workspace isolation is not yet available — every session uses this one workspace.",
  searchIcon: "⌕",
  inboxIcon: "⚑",
  closeIcon: "×",
  inboxReasonPlaceholder: "Why? (required)",
  inboxReasonConfirm: "Confirm reject",
  inboxReasonCancel: "Cancel",
  inboxActionFailed: "That didn't go through — try again.",
  searchNoResults: "No matches.",
  searchAsset: "ASSET",
  searchGlossaryTerm: "GLOSSARY TERM",
  searchBusinessMetric: "BUSINESS METRIC",
  overviewTitle: "Knowledge graph overview",
  overviewLoading: "Loading…",
  overviewError: "Could not load the overview — try again.",
  overviewAssetsTotal: "ASSETS",
  overviewDocumentation: "DOCUMENTED",
  overviewGraphFlakes: "GRAPH FACTS",
  overviewGraphNodes: "GRAPH NODES",
  overviewGraphEdges: "GRAPH EDGES",
  overviewGraphHealth: "GRAPH HEALTH",
  overviewCoverage: "Coverage",
  overviewGovernance: "Governance",
  overviewRecentActivity: "RECENT ACTIVITY",
  overviewNoActivity: "Nothing changed recently.",

  // ---- Explore (Plan 122a A3) ----
  exploreNoSeed: "Search or open an entity to explore its neighbourhood.",
  exploreLoading: "Loading the neighbourhood…",
  exploreError: "Could not load this neighbourhood — try again.",
  exploreFullscreenEnter: "Full screen",
  exploreFullscreenExit: "Exit full screen",
  exploreClose: "✕",
  exploreKind: "Kind",
  exploreKindHidden: "hidden by authorization",
  exploreId: "Id",
  exploreFqn: "Fully qualified name",
  exploreOpenEntity: "Open entity",
  explorePinToInvestigation: "Pin to investigation",
  explorePinned: "Pinned.",
  explorePinFailed: "Could not pin this — try again.",
  exploreEdgeAsserted: "ASSERTED",
  exploreEdgeDerived: "INFERRED",
  exploreTracePath: "Trace path to seed",
  exploreTruncated: "This picture is incomplete — some neighbours were cut off.",
  exploreRelationshipFilter: "Relationship",
  exploreClearFilter: "Clear filters",
  exploreTitle: "Explore",
  exploreBreadcrumbSeparator: "/",

  // ---- Entity (Plan 122a A3) ----
  entityNoId: "Search or open an entity to inspect it.",
  entityLoading: "Loading…",
  entityError: "Could not load this entity — try again.",
  entityOpenInExplorer: "Open in Explorer",
  entityPinToInvestigation: "Pin to investigation",
  entityFacts: "FACTS",
  entityFactsEmpty: "No outgoing relationships recorded for this entity.",
  entityFactAsserted: "asserted",
  entityFactDerived: "derived",
  entityContradictionTitle: "CONTRADICTION",
  entityContradictionDivider: "≠",
  entityContradictionHint: "Neither is hidden until you decide.",
  entityConfirm: "Confirm — these disagree",
  entityDismiss: "Dismiss — not a conflict",
  entityDismissTitle: "Dismiss this pair?",
  entityDismissBody: "It will not be flagged again. Both memories stay exactly as they are.",
  entityDismissCancel: "Cancel",
  entityContradictionConfirmed: "Recorded — the pair stays flagged, because agreeing it exists is not settling it.",
  entityContradictionDismissed: "Dismissed.",
  entityContradictionActionFailed: "That verdict could not be recorded — try again.",
  entityContradictionSideMissing: "not shown here — may be below this view's confidence floor",
  entityHistory: "HISTORY",
  entityHistoryEmpty: "No prior versions.",
  entityImpact: "IMPACT IF CHANGED",
  entityImpactEmpty: "Nothing else in the graph points to this entity yet.",

  // ---- TRACE group — Lineage, Paths, History, Evidence (Plan 122a A4) ----
  relatedTitle: "RELATED",
  traceRelatedExplore: "Explore",
  traceRelatedEntity: "Entity",
  traceRelatedContradictions: "Contradictions",
  traceNoSeed: "Search or open an entity to trace it.",
  traceLoading: "Loading…",
  traceError: "Could not load this — try again.",

  lineageTitle: "Lineage & impact",
  lineageDescription: "Where a fact came from, and what breaks if it changes.",
  lineageKpiFocus: "FOCUS",
  lineageKpiUpstream: "UPSTREAM",
  lineageKpiDownstream: "DOWNSTREAM",
  lineageKpiTruncated: "COMPLETE PICTURE",
  lineageTruncatedYes: "no — some edges cut off",
  lineageTruncatedNo: "yes",
  lineageColRelationship: "RELATIONSHIP",
  lineageColFrom: "FROM",
  lineageColTo: "TO",
  lineageColSource: "SOURCE",
  lineageColWhen: "WHEN",
  lineageEmpty: "No lineage edges recorded for this entity.",
  lineageChainArrow: "→",
  lineageChainSeparator: "·",
  lineageChainNodes: "nodes",
  lineageNoteTitle: "WHAT THIS SHOWS",
  lineageNoteBody: "Every asserted lineage edge within two hops of this entity, upstream and downstream. Nothing here is inferred — each edge was declared by a person, a connector, or an OpenLineage run event.",

  pathsTitle: "Path finder",
  pathsDescription: "How are these two things connected?",
  pathsKpiFrom: "FROM",
  pathsKpiTo: "TO",
  pathsKpiFound: "PATHS FOUND",
  pathsKpiTruncated: "COMPLETE PICTURE",
  pathsColPath: "PATH",
  pathsColRoute: "ROUTE",
  pathsColHops: "HOPS",
  pathsEmpty: "No path found between these two entities within the search bound.",
  pathsNoteTitle: "READ EVERY PATH, NOT JUST THE FIRST",
  pathsNoteBody: "A weak or roundabout connection is still shown, ranked by hop count — you decide whether it counts as a real connection.",
  pathsMissingEnds: "Provide both a from and a to entity to search.",
  pathsFromLabel: "From",
  pathsToLabel: "To",
  pathsSearch: "Find paths",

  historyTitle: "History & diff",
  historyDescription: "What the graph believed then, and what changed since.",
  historyKpiEntity: "ENTITY",
  historyKpiVersions: "VERSIONS",
  historyKpiLatest: "LATEST",
  historyKpiUpdatedBy: "LAST CHANGED BY",
  historyColVersion: "VERSION",
  historyColChange: "CHANGE",
  historyColWho: "WHO",
  historyColWhen: "WHEN",
  historyNoSummary: "no summary recorded",
  historyEmpty: "No prior versions recorded for this entity.",
  historyNoteTitle: "TIME IS GLOBAL",
  historyNoteBody: "Every version this entity has ever had, oldest first. Time-travel elsewhere in the console (Explore, Entity) reads against the same version history.",

  evidenceTitle: "Evidence",
  evidenceDescription: "Every governance finding, and the facts it rests on.",
  evidenceKpiFindings: "FINDINGS",
  evidenceKpiEntries: "EVIDENCE ENTRIES",
  evidenceKpiPending: "PENDING REVIEW",
  evidenceKpiPacks: "PACKS INVOLVED",
  evidenceColFact: "FACT",
  evidenceColSource: "PACK",
  evidenceColField: "FIELD",
  evidenceColStatus: "STATUS",
  evidenceEmpty: "No findings recorded yet.",
  evidenceNoteTitle: "WHERE THIS COMES FROM",
  evidenceNoteBody: "Every governance finding carries the facts that produced it — a rule concluded something, and this is what it looked at to conclude it.",
} as const;
