[package]
name = "graph-owl-lpg-io"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
graph-owl-core = { path = "../graph-owl-core" }
graph-owl-lpg = { path = "../graph-owl-lpg" }
thiserror.workspace = true
quick-xml.workspace = true
uuid.workspace = true
