[package]
name = "graph-owl-ontology"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
graph-owl-core = { path = "../graph-owl-core" }
graph-owl-reasoning-el = { path = "../graph-owl-reasoning-el" }
graph-owl-reasoning-ql = { path = "../graph-owl-reasoning-ql" }
graph-owl-rdf-io = { path = "../graph-owl-rdf-io" }
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
utoipa.workspace = true
uuid.workspace = true
