#!/usr/bin/env python3
"""A minimal read-only server rendering an asset with its context — Epic 36
Slice D: the smallest thing that proves the read API is renderable.

**Uses the generated client, never hand-rolled HTTP** — `graph_owl_read_client`
(Epic 36 Slice D's own addition to `sdk/python/`, generated by
`openapi-python-client` from the committed `openapi.json`). Building this
app found the contract had no query-parameter documentation mechanism at
all; fixed in `graph-owl-server/src/openapi.rs` — see
`36-reference-apps.md`'s Slice D account.

**One request per asset page** — `?fields=owners,tags,lineage,columns`
composes everything this page renders into the single `GET /assets/{id}`
call, not four. `render_asset_page`'s own doc explains why the composed
keys are read from `additional_properties` rather than typed fields.

Run it:

    python app.py --base-url http://localhost:8080 --port 8000
"""

from __future__ import annotations

import argparse
import html
from http.server import BaseHTTPRequestHandler, HTTPServer
from urllib.parse import parse_qs, urlparse
from uuid import UUID

import httpx

from graph_owl_read_client import Client
from graph_owl_read_client.api.default import get_assets, get_assets_id, get_assets_search
from graph_owl_read_client.models.asset import Asset
from graph_owl_read_client.models.problem import Problem
from graph_owl_read_client.types import Unset

PAGE = """<!doctype html>
<html><head><title>{title}</title></head>
<body>
<form method="get" action="/"><input name="q" value="{query}" placeholder="Search assets"><button>Search</button></form>
{body}
</body></html>"""


def escape(value: object) -> str:
    return html.escape(str(value)) if value is not None else ""


def render_search_page(client: Client, query: str | None) -> tuple[int, str]:
    if query:
        results = get_assets_search.sync(client=client, q=query)
        heading = f"Results for &ldquo;{escape(query)}&rdquo;"
    else:
        results = get_assets.sync(client=client, limit=50)
        heading = "All assets"

    # `sync()` returns `None` for any status this route does not document
    # as a success — the generated client's own way of saying "something
    # went wrong", distinct from a genuine zero-result page. Told apart
    # here rather than folded into the empty-list case, matching the
    # empty/error state distinction Slice D's own acceptance criterion asks
    # for.
    if results is None:
        body = "<h1>Something went wrong</h1><p><em>The catalog did not return a result.</em></p>"
        return 502, PAGE.format(title="graph-owl browse", query=escape(query or ""), body=body)
    assets = results.data

    # **The empty state, rendered distinguishably** — Slice D's own
    # acceptance criterion. A blank list and a page that never loaded look
    # identical to a user unless the "nothing here" case says so.
    if not assets:
        body = f"<h1>{heading}</h1><p><em>No assets found.</em></p>"
    else:
        rows = "".join(
            f'<li><a href="/assets/{asset.id}">{escape(asset.fully_qualified_name)}</a> '
            f"<small>({escape(asset.kind.value if hasattr(asset.kind, 'value') else asset.kind)})</small></li>"
            for asset in assets
        )
        body = f"<h1>{heading}</h1><ul>{rows}</ul>"

    return 200, PAGE.format(title="graph-owl browse", query=escape(query or ""), body=body)


def render_asset_page(client: Client, raw_id: str) -> tuple[int, str]:
    try:
        asset_id = UUID(raw_id)
    except ValueError:
        return 400, PAGE.format(title="Invalid id", query="", body="<h1>Invalid asset id</h1>")

    # One request, `fields=` composing everything below onto it — the
    # AC this whole slice exists to prove, not four separate calls.
    asset = get_assets_id.sync(
        client=client,
        id=asset_id,
        fields="owners,tags,lineage,columns",
    )

    # `sync()`'s return type is `Asset | Problem | None` — checked directly
    # against a real server, not assumed: a documented `404` decodes to a
    # `Problem`, not `None`; `None` is what the generated client returns
    # for a status this route does *not* document as success (a `500`, for
    # instance). Telling them apart matters here specifically — collapsing
    # both into one "error" page would make a routine "no such asset"
    # indistinguishable from a real backend failure.
    if isinstance(asset, Problem):
        # **Not found and policy-denied render the same page** — Slice B's
        # own discovery (default-deny authorization) applies here too: this
        # reference app has no way to tell "no such asset" from "you may
        # not see it", and presenting them differently would be inventing a
        # distinction the API itself does not make (`04-api-conventions.md`'s
        # own "absent is absent" rule, the same property `04d-mcp`'s
        # `NotFound` rests on).
        return 404, PAGE.format(
            title="Not found",
            query="",
            body="<h1>Not found</h1><p><em>No such asset, or it is not visible to you.</em></p>",
        )

    if asset is None:
        return 502, PAGE.format(
            title="Something went wrong",
            query="",
            body="<h1>Something went wrong</h1><p><em>The catalog did not return a result.</em></p>",
        )

    return 200, PAGE.format(title=asset.fully_qualified_name, query="", body=render_asset_detail(asset))


def render_asset_detail(asset: Asset) -> str:
    # `tags`/`lineage`/`columns` are `fields=`'s own composed keys, not part
    # of the `Asset` schema itself — a real, structural finding recorded in
    # `36-reference-apps.md`'s defect log: a strictly-typed generated client
    # can only reach them through `additional_properties`, untyped, because
    # the OpenAPI contract does not describe `Asset` growing these fields
    # conditionally on the request's own `?fields=` value.
    extra = asset.additional_properties

    owners = "" if isinstance(asset.owners, Unset) or not asset.owners else "".join(
        f"<li>{escape(owner.display_name if hasattr(owner, 'display_name') else owner)}</li>" for owner in asset.owners
    )
    tags = extra.get("tags") or []
    tags_html = "".join(f"<li>{escape(tag)}</li>" for tag in tags) if tags else "<li><em>none</em></li>"

    lineage = extra.get("lineage") or {}
    lineage_nodes = lineage.get("nodes") if isinstance(lineage, dict) else None
    lineage_html = (
        "".join(f"<li>{escape(node.get('fullyQualifiedName', node))}</li>" for node in lineage_nodes)
        if lineage_nodes
        else "<li><em>none</em></li>"
    )

    columns = extra.get("columns") or []
    columns_html = (
        "".join(f"<li>{escape(col.get('name', col))}</li>" for col in columns)
        if columns
        else "<li><em>none</em></li>"
    )

    description = asset.description if asset.description and not isinstance(asset.description, Unset) else "<em>none</em>"

    return f"""
    <h1>{escape(asset.fully_qualified_name)}</h1>
    <p>Kind: {escape(asset.kind.value if hasattr(asset.kind, 'value') else asset.kind)}</p>
    <p>Description: {escape(description) if description != "<em>none</em>" else description}</p>
    <h2>Owners</h2><ul>{owners or "<li><em>none</em></li>"}</ul>
    <h2>Tags</h2><ul>{tags_html}</ul>
    <h2>Lineage</h2><ul>{lineage_html}</ul>
    <h2>Columns</h2><ul>{columns_html}</ul>
    """


def make_handler(client: Client) -> type[BaseHTTPRequestHandler]:
    class Handler(BaseHTTPRequestHandler):
        def do_GET(self) -> None:  # noqa: N802 (http.server's own naming)
            parsed = urlparse(self.path)

            try:
                if parsed.path == "/":
                    query = (parse_qs(parsed.query).get("q") or [None])[0]
                    status, body = render_search_page(client, query)
                elif parsed.path.startswith("/assets/"):
                    status, body = render_asset_page(client, parsed.path.removeprefix("/assets/"))
                else:
                    status, body = 404, "<h1>Not found</h1>"
            except httpx.HTTPError as exc:
                # **The error state, rendered distinguishably** — the third
                # of Slice D's three required states (empty, error,
                # filtered/not-found). A backend outage must not look like
                # an empty catalog. This is specifically a *connection*
                # failure (the server unreachable, not merely answering
                # with an error) — an unexpected HTTP status is handled
                # inside `render_search_page`/`render_asset_page` themselves,
                # since the generated client's default
                # `raise_on_unexpected_status=False` means it returns `None`
                # for those rather than raising `UnexpectedStatus` (checked
                # directly against the generated code, not assumed).
                status, body = 502, f"<h1>Something went wrong</h1><p>{escape(exc)}</p>"

            self.send_response(status)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.end_headers()
            self.wfile.write(body.encode("utf-8"))

        def log_message(self, format: str, *args: object) -> None:  # noqa: A002
            pass  # quiet by default; a real deployment would wire real logging

    return Handler


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base-url", default="http://localhost:8080")
    parser.add_argument("--port", type=int, default=8000)
    args = parser.parse_args(argv)

    client = Client(base_url=args.base_url)
    server = HTTPServer(("127.0.0.1", args.port), make_handler(client))
    print(f"browsing {args.base_url} at http://127.0.0.1:{args.port}")
    server.serve_forever()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
